### PR TITLE
A bootstrapping tale - bootstraps the generator plugin and compiles the plugin with its own output

### PR DESCRIPTION
**Pull request by menduz**
This PR chronologically
1. fine tunes the Go code generator and fixes some issues with the `protobuf.zig` library
2. creates a Zig native plugin for `protoc`
3. fine tunes the plugin's output until the plugin can compile itself with the output of the previous run
4. removes the go dependency

### CODE REVIEW

**Comment by Arwalk** [comment]
Very cool work. But take your time, i feel like we don't need to rush the bootstrapped generator. I would prefer if we had a complete implementation before, release it with a "simple" generator, then work on the bootstrapping.

If i can help you with anything, don't hesitate, but it's obvious that you're at ease with the code base already.

**Comment by menduz** [comment]
Bootstrapping the generator was the most fun way I've found to fix some issues, I'll see where it leads to

**Comment by Arwalk** [comment]
> Bootstrapping the generator was the most fun way I've found to fix some issues, I'll see where it leads to

I was just about to write that if you're enjoying doing it, i can't really stop you. :)

**Comment by menduz** [comment]
it is alive @Arwalk :evil-laughter:

a couple more fixes on packed arrays + tests and I'll start polishing it

**Comment by Arwalk** [comment]
> it is alive @Arwalk :evil-laughter:
> 
> a couple more fixes on packed arrays + tests and I'll start polishing it

You're a hero. I think we'll be able to announce a first release after this. I can't thank you enough.

**Pull request merged**
